// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjp5zB40qvt5t2u8VShkZQ5F8Os-sFShM',
    appId: '1:744982811171:web:c288834e67b2cab5509796',
    messagingSenderId: '744982811171',
    projectId: 'harvestlink-99581',
    authDomain: 'harvestlink-99581.firebaseapp.com',
    storageBucket: 'harvestlink-99581.appspot.com',
    measurementId: 'G-Z81KD2K00M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAer0re1yI9y5cbq1lNxXcfYxT7kcb_SMc',
    appId: '1:744982811171:android:5f395782f227d643509796',
    messagingSenderId: '744982811171',
    projectId: 'harvestlink-99581',
    storageBucket: 'harvestlink-99581.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQ0ingLxsdQoBmXoGO_xmWXVYtKa2XEV0',
    appId: '1:744982811171:ios:3eaa6e14b6079538509796',
    messagingSenderId: '744982811171',
    projectId: 'harvestlink-99581',
    storageBucket: 'harvestlink-99581.appspot.com',
    androidClientId: '744982811171-tgkqgqft528n6tqfdd9k5t70d3ehhupp.apps.googleusercontent.com',
    iosClientId: '744982811171-0en2ll7nghnon7dfsn60btutb2a529h1.apps.googleusercontent.com',
    iosBundleId: 'com.example.harvestDelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQ0ingLxsdQoBmXoGO_xmWXVYtKa2XEV0',
    appId: '1:744982811171:ios:7b496cad0783eb72509796',
    messagingSenderId: '744982811171',
    projectId: 'harvestlink-99581',
    storageBucket: 'harvestlink-99581.appspot.com',
    androidClientId: '744982811171-tgkqgqft528n6tqfdd9k5t70d3ehhupp.apps.googleusercontent.com',
    iosClientId: '744982811171-49lqf246qlrodam9h0bbjakipl8gq2nl.apps.googleusercontent.com',
    iosBundleId: 'com.example.harvestDelivery.RunnerTests',
  );
}
